### ISSUE TITLE
Url needs to change to https

### ISSUE THREAD

**Issue by ravenbyron** [nounoursheureux/hubot-xkcd#3]
This is no longer working as robot.http doesn't follow the redirect to https causing an error...  changing it to https fixes it...

**Comment by eyenx** [comment]
+1

**Comment by eyenx** [comment]
The Source is fine here. But on npmjs.com it is not. 

https://www.npmjs.com/package/hubot-xkcd

**Comment by wbrbr** [comment]
@eyenx I updated the npm package, is it working now ?

**Comment by eyenx** [comment]
Works perfectly. Thank you!

**Comment by wbrbr** [comment]
:+1:
